### ISSUE TITLE
Documentation to-do list

### ISSUE THREAD

**Issue by ml-evs** [datalab-org/datalab#184]
From https://github.com/the-grey-group/datalabvue/pull/181:

- [x] Write design and deployment docs then clean up our current README (related #14)
- [x] Investigate OpenAPI + mkdocs, as well as flask + OpenAPI...
- [x] Automatically get docstrings from all modules (see mkdocstrings docs)
- [x] Inheritance of docstrings for pydantic models
