### ISSUE TITLE
v0.5.0 Release checklist

### ISSUE THREAD

**Issue by ml-evs** [datalab-org/datalab#927]
Just a place for me to collect things to do before the big upcoming release:

- [x] Update CHANGELOG
- [ ] Update ROADMAP (if it exists by then)
- [x] Update app version number (if https://github.com/datalab-org/datalab/pull/906 is not done by then)
- [x] Write release summary including possible migration notes
- [x] Review milestones

And then in other repos:

- [x] Adjust supported version for Python API client
- [x] Update ansible playbook supported versions

**Comment by ml-evs** [comment]
I am considering v0.5.0 ready to go, will close this issue after updating the changelog.
